### ISSUE TITLE
Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by porismuu** [snaildos/Fifo-Browser#129]
Download and launch the project
not working, what is missing or wrong?

node -v   v16.16.0
python -V   Python 3.10.6
yarn --version   1.22.19

$ yarn install --save --legacy-peer-deps # Install needed depedencies.
$ yarn build # Compile Fifo code and rebuild modules.
$ yarn dev # Run Fifo in development mode

VM338:7 Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'

<img src="https://gcdnb.pbrd.co/images/UePPLi59QIcx.png?o=1">

Console

```
G:\project\fifo-1-2-1>yarn dev
yarn run v1.22.19
$ cross-env START=1 npm run watch
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> Fifo@1.2.1 watch
> concurrently "npm run dev-renderer" "npm run dev-webpack"

[0] npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[1] npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[0]
[0] > Fifo@1.2.1 dev-renderer
[0] > cross-env DEV=1 webpack serve --config webpack.config.renderer.js
[0]
[1]
[1] > Fifo@1.2.1 dev-webpack
[1] > cross-env DEV=1 webpack
[1]
[0] [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
[0]     at Command.<anonymous> (G:\project\fifo-1-2-1\node_modules\@webpack-cli\serve\lib\index.js:146:35)
[0]     at async Promise.all (index 1)
[0]     at async Command.<anonymous> (G:\project\fifo-1-2-1\node_modules\webpack-cli\lib\webpack-cli.js:1674:7)
[0] npm run dev-renderer exited with code 2
[1] asset main.bundle.js 9.53 MiB [emitted] (name: main)
[1] asset preload.js 4.22 KiB [emitted] [from: node_modules/@cliqz/adblocker-electron-preload/dist/preload.cjs.js] [copied]
[1] runtime modules 2.15 KiB 6 modules
[1] modules by path ./node_modules/ 3.41 MiB 554 modules
[1] modules by path ./src/ 157 KiB
[1]   modules by path ./src/main/ 130 KiB 38 modules
[1]   modules by path ./src/utils/*.ts 15.6 KiB 10 modules
[1]   modules by path ./src/constants/*.ts 9.97 KiB 6 modules
[1]   modules by path ./src/common/ 945 bytes
[1]     ./src/common/webui.ts 331 bytes [built] [code generated]
[1]     + 2 modules
[1] modules by path external "require(/ 168 bytes
[1]   external "require(\"electron\")" 42 bytes [built] [code generated]
[1]   external "require(\"os\")" 42 bytes [built] [code generated]
[1]   external "require(\"path\")" 42 bytes [built] [code generated]
[1]   external "require(\"fs\")" 42 bytes [built] [code generated]
[1] + 19 modules
[1] webpack 5.68.0 compiled successfully in 8871 ms
[1]
[1] asset view-preload.bundle.js 66.4 KiB [emitted] (name: view-preload)
[1] asset popup-preload.bundle.js 2.36 KiB [emitted] (name: popup-preload)
[1] asset extensions-preload.bundle.js 296 bytes [emitted] (name: extensions-preload)
[1] runtime modules 221 bytes 1 module
[1] modules by path ./src/ 33.9 KiB
[1]   modules by path ./src/preloads/ 17.9 KiB 10 modules
[1]   modules by path ./src/utils/*.ts 2.43 KiB 2 modules
[1]   modules by path ./src/constants/*.ts 6.99 KiB 2 modules
[1]   modules by path ./src/renderer/constants/*.ts 6.54 KiB 2 modules
[1] modules by path ./node_modules/@electron/remote/ 23.7 KiB
[1]   modules by path ./node_modules/@electron/remote/dist/src/renderer/*.js 18.1 KiB 3 modules
[1]   modules by path ./node_modules/@electron/remote/dist/src/common/*.js 5.6 KiB
[1]     ./node_modules/@electron/remote/dist/src/common/type-utils.js 3.96 KiB [built] [code generated]
[1]     + 2 modules
[1]   ./node_modules/@electron/remote/renderer/index.js 49 bytes [built] [code generated]
[1] external "require(\"electron\")" 42 bytes [built] [code generated]
[1] webpack 5.68.0 compiled successfully in 6293 ms
[1] npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[1]
[1] > Fifo@1.2.1 start
[1] > electron .
[1]
[1]
[1]
[1] DevTools listening on ws://127.0.0.1:9222/devtools/browser/01346223-fa7f-4087-b59d-d834c575210a
[1] (node:3036) electron: Failed to load URL: http://localhost:4444/search.html with error: ERR_CONNECTION_REFUSED
[1] (Use `electron --trace-warnings ...` to show where the warning was created)
[1] (node:3036) UnhandledPromiseRejectionWarning: Error: ERR_CONNECTION_REFUSED (-102) loading 'http://localhost:4444/search.html'
[1]     at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
[1]     at EventEmitter.failListener (node:electron/js2c/browser_init:161:7860)
[1]     at EventEmitter.emit (node:events:390:28)
[1] (node:3036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[1] (node:3036) electron: Failed to load URL: http://localhost:4444/preview.html with error: ERR_CONNECTION_REFUSED
[1] (node:3036) UnhandledPromiseRejectionWarning: Error: ERR_CONNECTION_REFUSED (-102) loading 'http://localhost:4444/preview.html'
[1]     at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
[1]     at EventEmitter.failListener (node:electron/js2c/browser_init:161:7860)
[1]     at EventEmitter.emit (node:events:390:28)
[1] (node:3036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[1] (node:3036) electron: Failed to load URL: http://localhost:4444/app.html with error: ERR_CONNECTION_REFUSED
[1] (node:3036) UnhandledPromiseRejectionWarning: Error: ERR_CONNECTION_REFUSED (-102) loading 'http://localhost:4444/app.html'
[1]     at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)
[1]     at EventEmitter.failListener (node:electron/js2c/browser_init:161:7860)
[1]     at EventEmitter.emit (node:events:390:28)
[1] (node:3036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[1] (node:3036) UnhandledPromiseRejectionWarning: Error: Script failed to execute, this normally means an error was thrown. Check the renderer console for the error.
[1]     at node:electron/js2c/renderer_init:93:395
[1]     at EventEmitter.<anonymous> (node:electron/js2c/renderer_init:81:375)
[1]     at EventEmitter.emit (node:events:390:28)
[1]     at Object.onMessage (node:electron/js2c/renderer_init:69:833)
[1] (node:3036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by porismuu** [comment]
@snaildos

**Comment by snaildos** [comment]
@porismuu Do you want to discuss this on our forums or discord?
It's a bit annoying on GitHub,
either way, we do not recommend you to use development mode without actually developing. However, this error should be dismissed and the browser should load a couple of seconds later. If not, can you open the full error by left clicking on VM338:7?
Kind regards,
Snail

**Comment by porismuu** [comment]
> 
 VM3,

```
        const {ipcRenderer} = require('electron');
        const resizeObserver = new ResizeObserver(([{ contentRect }]) => {
          ipcRenderer.send('resize-height');
        });
        const app = document.getElementById('app');
        resizeObserver.observe(app);
      
```

  **resizeObserver.observe(app);**

**Comment by snaildos** [comment]
> > 
> 
> VM3,
> 
> ```
>         const {ipcRenderer} = require('electron');
>         const resizeObserver = new ResizeObserver(([{ contentRect }]) => {
>           ipcRenderer.send('resize-height');
>         });
>         const app = document.getElementById('app');
>         resizeObserver.observe(app);
>       
> ```
> 
> **resizeObserver.observe(app);** //Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.

Is development mode 100% needed?

**Comment by porismuu** [comment]
> > > 
> > 
> > 
> > VM3,
> > ```
> >         const {ipcRenderer} = require('electron');
> >         const resizeObserver = new ResizeObserver(([{ contentRect }]) => {
> >           ipcRenderer.send('resize-height');
> >         });
> >         const app = document.getElementById('app');
> >         resizeObserver.observe(app);
> >       
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **resizeObserver.observe(app);** //Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
> 
> Is development mode 100% needed?

I just want to start.
What is the code to run?

**Comment by snaildos** [comment]
> > > > 
> > > 
> > > 
> > > VM3,
> > > ```
> > >         const {ipcRenderer} = require('electron');
> > >         const resizeObserver = new ResizeObserver(([{ contentRect }]) => {
> > >           ipcRenderer.send('resize-height');
> > >         });
> > >         const app = document.getElementById('app');
> > >         resizeObserver.observe(app);
> > >       
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > **resizeObserver.observe(app);** //Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
> > 
> > 
> > Is development mode 100% needed?
> 
> I just want to start. What is the code to run?

Preferably, download a stable release from GitHub on our release page,
With CLI though, I recommend you delete the downloaded git clone, re-gitclone and type:
```
yarn
yarn build
yarn start
```
Hope that helps!

**Comment by porismuu** [comment]
> > > > > 
> > > > 
> > > > 
> > > > VM3,
> > > > ```
> > > >         const {ipcRenderer} = require('electron');
> > > >         const resizeObserver = new ResizeObserver(([{ contentRect }]) => {
> > > >           ipcRenderer.send('resize-height');
> > > >         });
> > > >         const app = document.getElementById('app');
> > > >         resizeObserver.observe(app);
> > > >       
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > **resizeObserver.observe(app);** //Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
> > > 
> > > 
> > > Is development mode 100% needed?
> > 
> > 
> > I just want to start. What is the code to run?
> 
> Preferably, download a stable release from GitHub on our release page, With CLI though, I recommend you delete the downloaded git clone, re-gitclone and type:
> 
> ```
> yarn
> yarn build
> yarn start
> ```
> 
> Hope that helps!

Wonderful. this worked.
I'm waiting for the new update.

great job.

**Comment by snaildos** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > VM3,
> > > > > ```
> > > > >         const {ipcRenderer} = require('electron');
> > > > >         const resizeObserver = new ResizeObserver(([{ contentRect }]) => {
> > > > >           ipcRenderer.send('resize-height');
> > > > >         });
> > > > >         const app = document.getElementById('app');
> > > > >         resizeObserver.observe(app);
> > > > >       
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > **resizeObserver.observe(app);** //Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
> > > > 
> > > > 
> > > > Is development mode 100% needed?
> > > 
> > > 
> > > I just want to start. What is the code to run?
> > 
> > 
> > Preferably, download a stable release from GitHub on our release page, With CLI though, I recommend you delete the downloaded git clone, re-gitclone and type:
> > ```
> > yarn
> > yarn build
> > yarn start
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope that helps!
> 
> Wonderful. this worked. I'm waiting for the new update.
> 
> great job.

Cool! Just curious, why not download the installer from the releases? Installer has auto-update functionality and is more stable then running of a branch on GitHub?

**Comment by porismuu** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > VM3,
> > > > > > ```
> > > > > >         const {ipcRenderer} = require('electron');
> > > > > >         const resizeObserver = new ResizeObserver(([{ contentRect }]) => {
> > > > > >           ipcRenderer.send('resize-height');
> > > > > >         });
> > > > > >         const app = document.getElementById('app');
> > > > > >         resizeObserver.observe(app);
> > > > > >       
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > **resizeObserver.observe(app);** //Uncaught TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.
> > > > > 
> > > > > 
> > > > > Is development mode 100% needed?
> > > > 
> > > > 
> > > > I just want to start. What is the code to run?
> > > 
> > > 
> > > Preferably, download a stable release from GitHub on our release page, With CLI though, I recommend you delete the downloaded git clone, re-gitclone and type:
> > > ```
> > > yarn
> > > yarn build
> > > yarn start
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Hope that helps!
> > 
> > 
> > Wonderful. this worked. I'm waiting for the new update.
> > great job.
> 
> Cool! Just curious, why not download the installer from the releases? Installer has auto-update functionality and is more stable then running of a branch on GitHub?

I will test it and let you know.
I'm not entirely sure, but I'll do a few tests.

**Comment by snaildos** [comment]
Cool, leave a :star: on this project if you can, I'm going to close the issue.
